package Main;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Nyo
 */
public class Calculadora extends javax.swing.JFrame {
    private boolean haynumero=false, esdecimal=false, hayAns=false;
    private double memoria;
    private int contparentesis=0;
    
    public Calculadora() {
        initComponents();
       //img1.setIcon(new ImageIcon("src/Imagenes/LogoUlima.png"));
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/LogoUlima.png"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(img1.getWidth(), img1.getHeight(), Image.SCALE_DEFAULT));
        img1.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Button_Exp = new javax.swing.JButton();
        Button_Ans = new javax.swing.JButton();
        Button_N1 = new javax.swing.JButton();
        Button_N4 = new javax.swing.JButton();
        Button_N5 = new javax.swing.JButton();
        Button_N3 = new javax.swing.JButton();
        Button_N6 = new javax.swing.JButton();
        Button_C = new javax.swing.JButton();
        Button_Multiplicacion = new javax.swing.JButton();
        Button_MS = new javax.swing.JButton();
        Button_N9 = new javax.swing.JButton();
        Button_Division = new javax.swing.JButton();
        Button_N2 = new javax.swing.JButton();
        Button_N7 = new javax.swing.JButton();
        Button_N8 = new javax.swing.JButton();
        Button_Decimal = new javax.swing.JButton();
        Button_N0 = new javax.swing.JButton();
        Button_igual = new javax.swing.JButton();
        Button_Resta = new javax.swing.JButton();
        Button_Suma = new javax.swing.JButton();
        Button_Retroseso = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtPantalla = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        Button_ParéntesisL = new javax.swing.JButton();
        Button_ParéntesisR = new javax.swing.JButton();
        img1 = new javax.swing.JLabel();
        Operacional = new javax.swing.JButton();
        Graficadora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora ");

        Button_Exp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Exp.setText("^");
        Button_Exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExpActionPerformed(evt);
            }
        });

        Button_Ans.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Ans.setText("Ans");
        Button_Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AnsActionPerformed(evt);
            }
        });

        Button_N1.setBackground(new java.awt.Color(255, 255, 255));
        Button_N1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N1.setText("1");
        Button_N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N1ActionPerformed(evt);
            }
        });

        Button_N4.setBackground(new java.awt.Color(255, 255, 255));
        Button_N4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N4.setText("4");
        Button_N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N4ActionPerformed(evt);
            }
        });

        Button_N5.setBackground(new java.awt.Color(255, 255, 255));
        Button_N5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N5.setText("5");
        Button_N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N5ActionPerformed(evt);
            }
        });

        Button_N3.setBackground(new java.awt.Color(255, 255, 255));
        Button_N3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N3.setText("3");
        Button_N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N3ActionPerformed(evt);
            }
        });

        Button_N6.setBackground(new java.awt.Color(255, 255, 255));
        Button_N6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N6.setText("6");
        Button_N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N6ActionPerformed(evt);
            }
        });

        Button_C.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_C.setForeground(new java.awt.Color(251, 54, 1));
        Button_C.setText("C");
        Button_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CActionPerformed(evt);
            }
        });

        Button_Multiplicacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Multiplicacion.setText("*");
        Button_Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MultiplicacionActionPerformed(evt);
            }
        });

        Button_MS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_MS.setForeground(new java.awt.Color(251, 115, 0));
        Button_MS.setText("MS");
        Button_MS.setToolTipText("");
        Button_MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MSActionPerformed(evt);
            }
        });

        Button_N9.setBackground(new java.awt.Color(255, 255, 255));
        Button_N9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N9.setText("9");
        Button_N9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N9ActionPerformed(evt);
            }
        });

        Button_Division.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Division.setText("/");
        Button_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DivisionActionPerformed(evt);
            }
        });

        Button_N2.setBackground(new java.awt.Color(255, 255, 255));
        Button_N2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N2.setText("2");
        Button_N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N2ActionPerformed(evt);
            }
        });

        Button_N7.setBackground(new java.awt.Color(255, 255, 255));
        Button_N7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N7.setText("7");
        Button_N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N7ActionPerformed(evt);
            }
        });

        Button_N8.setBackground(new java.awt.Color(255, 255, 255));
        Button_N8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N8.setText("8");
        Button_N8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N8ActionPerformed(evt);
            }
        });

        Button_Decimal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Decimal.setText(".");
        Button_Decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DecimalActionPerformed(evt);
            }
        });

        Button_N0.setBackground(new java.awt.Color(255, 255, 255));
        Button_N0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N0.setText("0");
        Button_N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N0ActionPerformed(evt);
            }
        });

        Button_igual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_igual.setText("=");
        Button_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_igualActionPerformed(evt);
            }
        });

        Button_Resta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Resta.setText("-");
        Button_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RestaActionPerformed(evt);
            }
        });

        Button_Suma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Suma.setText("+");
        Button_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SumaActionPerformed(evt);
            }
        });

        Button_Retroseso.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Button_Retroseso.setText("<--");
        Button_Retroseso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RetrosesoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, -1));

        txtPantalla.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtPantalla.setForeground(new java.awt.Color(0, 51, 153));
        txtPantalla.setToolTipText("");
        txtPantalla.setBorder(null);
        txtPantalla.setFocusable(false);
        txtPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantallaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 50));

        txtResultado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultado.setText(" ");
        txtResultado.setBorder(null);
        txtResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtResultado.setFocusable(false);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 260, 30));

        Button_ParéntesisL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_ParéntesisL.setText("(");
        Button_ParéntesisL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ParéntesisLActionPerformed(evt);
            }
        });

        Button_ParéntesisR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_ParéntesisR.setText(")");
        Button_ParéntesisR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ParéntesisRActionPerformed(evt);
            }
        });

        Operacional.setText("Operacional");
        Operacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperacionalActionPerformed(evt);
            }
        });

        Graficadora.setText("Graficadora");
        Graficadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficadoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Button_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Button_N1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(Button_N4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Button_N7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Button_N8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Button_N5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Button_N2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Button_N9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Button_N6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Button_N3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button_MS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button_Retroseso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button_N0, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Button_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Button_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Button_ParéntesisL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Button_ParéntesisR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Button_Suma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Button_Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Button_Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Button_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(Button_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Operacional)
                        .addGap(0, 0, 0)
                        .addComponent(Graficadora)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Operacional)
                    .addComponent(Graficadora))
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_MS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_C, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Retroseso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_N7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_N8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_N9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_N4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_N5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_N6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_N1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_N2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_N3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_N0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Button_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Button_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_ParéntesisL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Button_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_ParéntesisR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Button_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Botones numericos
    private void Button_N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N1ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"1");
        haynumero=true;
        hayAns=true;
    }//GEN-LAST:event_Button_N1ActionPerformed

    private void Button_N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N2ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"2");
        haynumero=true;
        hayAns=true;

    }//GEN-LAST:event_Button_N2ActionPerformed

    private void Button_N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N3ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"3");
        haynumero=true;
        hayAns=true;
    }//GEN-LAST:event_Button_N3ActionPerformed

    private void Button_N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N4ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"4");
        haynumero=true;
        hayAns=true;     
    }//GEN-LAST:event_Button_N4ActionPerformed

    private void Button_N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N5ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"5");
        haynumero=true;
        hayAns=true;
    }//GEN-LAST:event_Button_N5ActionPerformed

    private void Button_N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N6ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"6");
        haynumero=true;
        hayAns=true;           
    }//GEN-LAST:event_Button_N6ActionPerformed

    private void Button_N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N7ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"7");
        haynumero=true;
        hayAns=true;
    }//GEN-LAST:event_Button_N7ActionPerformed

    private void Button_N8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N8ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"8");
        haynumero=true;
        hayAns=true;   
    }//GEN-LAST:event_Button_N8ActionPerformed

    private void Button_N9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N9ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"9");
        haynumero=true;
        hayAns=true;   
    }//GEN-LAST:event_Button_N9ActionPerformed

    private void Button_N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N0ActionPerformed
        if (esdecimal==true) {
            txtPantalla.setText(txtPantalla.getText()+"0");
        }else{
            txtPantalla.setText(txtPantalla.getText()+"0");
            haynumero=true;
            hayAns=true;
        }
    }//GEN-LAST:event_Button_N0ActionPerformed
    //Botón la función de punto decimal
    private void Button_DecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DecimalActionPerformed
        if (esdecimal==true) {
            //Ya tiene punto decimal y no lo vuelve a asignar
        }else{
            if(haynumero==true){
                if (!txtPantalla.getText().endsWith("+") && !txtPantalla.getText().endsWith("-") && !txtPantalla.getText().endsWith("*") &&
                        !txtPantalla.getText().endsWith("/")) {
                    txtPantalla.setText(txtPantalla.getText()+".");
                    esdecimal=true;           
                }
            }
        }
    }//GEN-LAST:event_Button_DecimalActionPerformed
    //Botón de la función de suma
    private void Button_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SumaActionPerformed
        if(haynumero==true){
            if((txtPantalla.getText().endsWith("+") || txtPantalla.getText().endsWith("-") || txtPantalla.getText().endsWith("*") ||
                txtPantalla.getText().endsWith("/") || txtPantalla.getText().endsWith("^")|| txtPantalla.getText().endsWith("(")) ||
                txtPantalla.getText().endsWith(".")){
            }else{
                txtPantalla.setText(txtPantalla.getText()+"+");
                esdecimal=false;
                hayAns=false;
            }
        }
    }//GEN-LAST:event_Button_SumaActionPerformed
//Botón de la función de resta
    private void Button_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RestaActionPerformed
        if((txtPantalla.getText().endsWith("+") || txtPantalla.getText().endsWith("-")) || txtPantalla.getText().endsWith(".")){
        }else{
            txtPantalla.setText(txtPantalla.getText()+"-");
            esdecimal=false;
            hayAns=false;
        }       
    }//GEN-LAST:event_Button_RestaActionPerformed
//Botón de la función de multiplicar
    private void Button_MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MultiplicacionActionPerformed
        if(haynumero==true){
            if((txtPantalla.getText().endsWith("+") || txtPantalla.getText().endsWith("-") || txtPantalla.getText().endsWith("*") ||
                txtPantalla.getText().endsWith("/") || txtPantalla.getText().endsWith("^")|| txtPantalla.getText().endsWith("(")) ||
                txtPantalla.getText().endsWith(".")){
            }else{
                txtPantalla.setText(txtPantalla.getText()+"*");
                esdecimal=false;
                hayAns=false;
            }   
        }
    }//GEN-LAST:event_Button_MultiplicacionActionPerformed
//Botón de la función de división
    private void Button_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DivisionActionPerformed
        if(haynumero==true){
            if((txtPantalla.getText().endsWith("+") || txtPantalla.getText().endsWith("-") || txtPantalla.getText().endsWith("*") ||
                txtPantalla.getText().endsWith("/") || txtPantalla.getText().endsWith("^")|| txtPantalla.getText().endsWith("(")) ||
                txtPantalla.getText().endsWith(".")){
            }else{
                txtPantalla.setText(txtPantalla.getText()+"/");
                esdecimal=false;
                hayAns=false;
            }    
        }
    }//GEN-LAST:event_Button_DivisionActionPerformed
//Botón de la función de igual
    private void Button_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_igualActionPerformed
        if(haynumero==true){
            if((txtPantalla.getText().endsWith("+") || txtPantalla.getText().endsWith("-") || txtPantalla.getText().endsWith("*") ||
                txtPantalla.getText().endsWith("/") || txtPantalla.getText().endsWith("^")|| txtPantalla.getText().endsWith("(")) ||
                    txtPantalla.getText().endsWith(".")){
            }else{
                if(contparentesis==0){
                    Conversión ref = new Conversión();
                    String expresion = txtPantalla.getText();
                    ref.setExpresion(expresion);
                    String expresionresultado = String.valueOf(ref.Valor());
                    memoria = Double.parseDouble(expresionresultado);
                    txtResultado.setText(expresionresultado);
                }else{
                    txtResultado.setText("Falta cerrar "+contparentesis+" paréntesis");
                }
            }
        }
    }//GEN-LAST:event_Button_igualActionPerformed

    private void Button_AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AnsActionPerformed
        String ans = String.valueOf(memoria);
        if (esdecimal==true) {
          
        }else{
            if(hayAns==false){
                txtPantalla.setText(txtPantalla.getText()+ans);
                haynumero=true;
                hayAns=true;
            }
        }      
    }//GEN-LAST:event_Button_AnsActionPerformed

    private void Button_ExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExpActionPerformed
        if(haynumero==true){
            if((txtPantalla.getText().endsWith("+") || txtPantalla.getText().endsWith("-") || txtPantalla.getText().endsWith("*") ||
                    txtPantalla.getText().endsWith("/") || txtPantalla.getText().endsWith("^")|| txtPantalla.getText().endsWith("(")) ||
                    txtPantalla.getText().endsWith(".")){
            }else{
                txtPantalla.setText(txtPantalla.getText()+"^");
                esdecimal=false;
                hayAns=false;
            }  
        }
    }//GEN-LAST:event_Button_ExpActionPerformed

//Botón con la función de C
    private void Button_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CActionPerformed
        txtPantalla.setText("");
        txtResultado.setText("");
        esdecimal=false;
        haynumero=false;
        hayAns=false;
        contparentesis=0;
    }//GEN-LAST:event_Button_CActionPerformed
 //Botón con la función de MS
    private void Button_MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MSActionPerformed
        memoria=0;
    }//GEN-LAST:event_Button_MSActionPerformed
//Botón con la función de RETROCEDER
    private void Button_RetrosesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RetrosesoActionPerformed
        if (txtPantalla.getText().length()>0) {
            if(txtPantalla.getText().endsWith("(")){
                contparentesis--;
            }
            if(txtPantalla.getText().endsWith(")")){
                contparentesis++;
            }
            txtPantalla.setText(txtPantalla.getText().substring(0,txtPantalla.getText().length()-1));
        }
        if (txtPantalla.getText().length()==0) {
            Button_CActionPerformed(evt);
        }      
    }//GEN-LAST:event_Button_RetrosesoActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void txtPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantallaActionPerformed

    private void Button_ParéntesisLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ParéntesisLActionPerformed
        if(txtPantalla.getText().endsWith("+") || txtPantalla.getText().endsWith("-") || txtPantalla.getText().endsWith("*")
                || txtPantalla.getText().endsWith("/") || txtPantalla.getText().endsWith("^") || 
                txtPantalla.getText().endsWith("(") || haynumero==false){      
            txtPantalla.setText(txtPantalla.getText()+"(");
            esdecimal=false;
            contparentesis++;
        } 
    }//GEN-LAST:event_Button_ParéntesisLActionPerformed

    private void Button_ParéntesisRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ParéntesisRActionPerformed
        if (contparentesis!=0) {
            if((txtPantalla.getText().endsWith("+") || txtPantalla.getText().endsWith("-") || txtPantalla.getText().endsWith("*") ||
                txtPantalla.getText().endsWith("/") || txtPantalla.getText().endsWith("^")|| txtPantalla.getText().endsWith("(")) ||
                    txtPantalla.getText().endsWith(".")){
            }else{
                txtPantalla.setText(txtPantalla.getText()+")");
                esdecimal=false;
                contparentesis--;
            }  
        }
    }//GEN-LAST:event_Button_ParéntesisRActionPerformed

    private void OperacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperacionalActionPerformed

    }//GEN-LAST:event_OperacionalActionPerformed

    private void GraficadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficadoraActionPerformed
        Graficadora grafica = new Graficadora();

        grafica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GraficadoraActionPerformed
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Ans;
    private javax.swing.JButton Button_C;
    private javax.swing.JButton Button_Decimal;
    private javax.swing.JButton Button_Division;
    private javax.swing.JButton Button_Exp;
    private javax.swing.JButton Button_MS;
    private javax.swing.JButton Button_Multiplicacion;
    private javax.swing.JButton Button_N0;
    private javax.swing.JButton Button_N1;
    private javax.swing.JButton Button_N2;
    private javax.swing.JButton Button_N3;
    private javax.swing.JButton Button_N4;
    private javax.swing.JButton Button_N5;
    private javax.swing.JButton Button_N6;
    private javax.swing.JButton Button_N7;
    private javax.swing.JButton Button_N8;
    private javax.swing.JButton Button_N9;
    private javax.swing.JButton Button_ParéntesisL;
    private javax.swing.JButton Button_ParéntesisR;
    private javax.swing.JButton Button_Resta;
    private javax.swing.JButton Button_Retroseso;
    private javax.swing.JButton Button_Suma;
    private javax.swing.JButton Button_igual;
    private javax.swing.JButton Graficadora;
    private javax.swing.JButton Operacional;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel img1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtPantalla;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
